eLMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

admin.site.site_header = "eLMS Administration"
admin.site.site_title = "eLMS Administration Portal"
admin.site.index_title = "Welcome to eLMS Administration Portal"


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('main.urls')),
    path('', include('discussion.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.std_login, name='std_login'),
    path('my/', views.myCourses, name='myCourses'),
    path('facultyCourses/', views.facultyCourses, name='facultyCourses'),
    path('login/', views.std_login, name='std_login'),
    path('logout/', views.std_logout, name='std_logout'),
    path('my/<int:code>/', views.course_page, name='course'),
    path('profile/<str:id>/', views.profile, name='profile'),
    path('facultyProfile/<str:id>/', views.profile, name='profile_faculty'),
    path('faculty/<int:code>/', views.course_page_faculty, name='faculty'),
    path('addAnnouncement/<int:code>/',
         views.addAnnouncement, name='addAnnouncement'),
    path('announecement/<int:code>/<int:id>/',
         views.deleteAnnouncement, name='deleteAnnouncement'),
    path('edit/<int:code>/<int:id>/',views.editAnnouncement, name='editAnnouncement'),
    path('update/<int:code>/<int:id>/',views.updateAnnouncement, name='updateAnnouncement'),
    path('addAssignment/<int:code>/', views.addAssignment, name='addAssignment'),
    path('assignment/<int:code>/<int:id>/',views.assignmentPage, name='assignmentPage'),
    path('assignments/<int:code>/', views.allAssignments, name='allAssignments'),
    path('student-assignments/<int:code>/', views.allAssignmentsSTD, name='student-assignments'),
    path('addSubmission/<int:code>/<int:id>/',views.addSubmission, name='addSubmission'),
     path('submission/<int:code>/<int:id>/',views.viewSubmission, name='submission'),
     path('gradeSubmission/<int:code>/<int:id>/<int:sub_id>',views.gradeSubmission, name='gradeSubmission'),
     path('course-material/<int:code>/',views.addCourseMaterial, name='addCourseMaterial'),
     path('course-material/<int:code>/<int:id>/',views.deleteCourseMaterial, name='deleteCourseMaterial'),
     path('courses/',views.courses, name='courses'),
     path('access/<int:code>/',views.access, name='access'),
     path('search/',views.search, name='search'),
     path('error/',views.error, name='error'),
]

main/models.py
from django.db import models
# Create your models here.


class Student(models.Model):
    student_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100, null=False)
    email = models.EmailField(max_length=100, null=True, blank=True)
    password = models.CharField(max_length=255, null=False)
    department = models.CharField(max_length=100, null=False)
    role = models.CharField(
        default="Student", max_length=100, null=False, blank=True)
    course = models.ManyToManyField(
        'Course', related_name='students', blank=True)
    photo = models.ImageField(upload_to='profile_pics', blank=True,
                              null=False, default='profile_pics/default_student.png')

    def delete(self, *args, **kwargs):
        if self.photo != 'profile_pics/default_student.png':
            self.photo.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Students'

    def __str__(self):
        return self.name


class Faculty(models.Model):
    faculty_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100, null=False)
    email = models.EmailField(max_length=100, null=True, blank=True)
    password = models.CharField(max_length=255, null=False)
    department = models.CharField(max_length=100, null=False)
    role = models.CharField(
        default="Faculty", max_length=100, null=False, blank=True)
    photo = models.ImageField(upload_to='profile_pics', blank=True,
                              null=False, default='profile_pics/default_faculty.png')

    def delete(self, *args, **kwargs):
        if self.photo != 'profile_pics/default_faculty.png':
            self.photo.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Faculty'

    def __str__(self):
        return self.name


class Course(models.Model):
    code = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255, null=False, unique=True)
    department = models.CharField(max_length=100, null=False)
    faculty = models.ForeignKey(
        Faculty, on_delete=models.SET_NULL, null=True, blank=True)
    studentKey = models.IntegerField(null=False, unique=True)
    facultyKey = models.IntegerField(null=False, unique=True)

    class Meta:
        unique_together = ('code', 'department', 'name')
        verbose_name_plural = "Courses"

    def __str__(self):
        return self.name


class Announcement(models.Model):
    course_code = models.ForeignKey(
        Course, on_delete=models.CASCADE, null=False)
    title = models.CharField(max_length=255, null=False)
    description = models.TextField(max_length=2000, null=False)
    datetime = models.DateTimeField(auto_now_add=True, null=False)

    class Meta:
        verbose_name_plural = "Announcements"
        ordering = ['-datetime']

    def __str__(self):
        return self.title


class Assignment(models.Model):
    course_code = models.ForeignKey(
        Course, on_delete=models.CASCADE, null=False)
    title = models.CharField(max_length=255, null=False)
    description = models.TextField(max_length=2000, null=False)
    datetime = models.DateTimeField(auto_now_add=True, null=False)
    deadline = models.DateTimeField(null=False)
    file = models.FileField(upload_to='assignments/', null=True, blank=True)
    marks = models.DecimalField(max_digits=6, decimal_places=2, null=False)

    class Meta:
        verbose_name_plural = "Assignments"
        ordering = ['-datetime']

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)


class Submission(models.Model):
    assignment = models.ForeignKey(
        Assignment, on_delete=models.CASCADE, null=False)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=False)
    file = models.FileField(upload_to='submissions/', null=True,)
    datetime = models.DateTimeField(auto_now_add=True, null=False)
    marks = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    status = models.CharField(max_length=100, null=True, blank=True)

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.student.name + " - " + self.assignment.title

    class Meta:
        unique_together = ('assignment', 'student')
        verbose_name_plural = "Submissions"
        ordering = ['datetime']


class Material(models.Model):
    course_code = models.ForeignKey(
        Course, on_delete=models.CASCADE, null=False)
    title = models.CharField(max_length=255, null=False)
    description = models.TextField(max_length=2000, null=False)
    datetime = models.DateTimeField(auto_now_add=True, null=False)
    file = models.FileField(upload_to='materials/', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Materials"
        ordering = ['-datetime']

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

main/views.py
import datetime
from django.shortcuts import redirect, render
from django.contrib import messages
from .models import Student, Course, Announcement, Assignment, Submission, Material, Faculty
from django.template.defaulttags import register
from django.db.models import Count, Q
from django.http import HttpResponseRedirect


def is_student_authorised(request, code):
    course = Course.objects.get(code=code)
    if request.session.get('student_id') and course in Student.objects.get(student_id=request.session['student_id']).course.all():
        return True
    else:
        return False


def is_faculty_authorised(request, code):
    if request.session.get('faculty_id') and code in Course.objects.filter(faculty_id=request.session['faculty_id']).values_list('code', flat=True):
        return True
    else:
        return False


# Login page for both student and faculty
def std_login(request):
    try:
        # If the user is already logged in, redirect to the course page
        if request.session.get('student_id'):
            return redirect('/my/')
        elif request.session.get('faculty_id'):
            return redirect('/facultyCourses/')
        else:
            # If the user is not logged in, display the login page
            if request.method == 'POST':
                id = request.POST["id"]
                password = (request.POST["password"])
                try:
                    # Checks if id matches any student, if no match found, checks if id matches any faculty
                    if Student.objects.filter(student_id=id).exists():
                        student = Student.objects.get(student_id=id)
                        if str(student.student_id) == id and str(student.password) == password:

                            request.session['student_id'] = id
                            return redirect('myCourses')
                        else:
                            # id matches but student password is wrong
                            messages.error(
                                request, 'Incorrect password. Please try again.', extra_tags='alert')
                            return redirect('std_login')

                    else:
                        # Checks if id matches any faculty
                        if Faculty.objects.filter(faculty_id=id).exists():
                            faculty = Faculty.objects.get(faculty_id=id)
                            if str(faculty.faculty_id) == id and str(faculty.password) == password:
                                request.session['faculty_id'] = id
                                return redirect('facultyCourses')

                            else:
                                # id matches but faculty password is wrong
                                messages.error(
                                    request, 'Incorrect password. Please try again.', extra_tags='alert')
                                return redirect('std_login')
                        else:
                            # id does not match any student or faculty
                            messages.error(
                                request, 'Incorrect user id. Please try again.', extra_tags='alert')
                            return redirect('std_login')
                except:
                    # id does not match any student or faculty
                    messages.error(
                        request, 'Invalid login credentials.', extra_tags='alert')
                    return redirect('std_login')

            else:
                return render(request, 'login_page.html')
    except:
        return render(request, 'error.html')


# Clears the session on logout
def std_logout(request):
    request.session.flush()
    return redirect('std_login')


# Display all courses (student view)
def myCourses(request):
    try:
        if request.session.get('student_id'):
            student = Student.objects.get(
                student_id=request.session['student_id'])
            courses = student.course.all()
            faculty = student.course.all().values_list('faculty_id', flat=True)

            context = {
                'courses': courses,
                'student': student,
                'faculty': faculty
            }

            return render(request, 'main/myCourses.html', context)
        else:
            return redirect('std_login')
    except:
        return render(request, 'error.html')


# Display all courses (faculty view)
def facultyCourses(request):
    try:
        if request.session['faculty_id']:
            faculty = Faculty.objects.get(
                faculty_id=request.session['faculty_id'])
            courses = Course.objects.filter(
                faculty_id=request.session['faculty_id'])
            # Student count of each course to show on the faculty page
            studentCount = Course.objects.all().annotate(student_count=Count('students'))

            studentCountDict = {}

            for course in studentCount:
                studentCountDict[course.code] = course.student_count

            @register.filter
            def get_item(dictionary, course_code):
                return dictionary.get(course_code)

            context = {
                'courses': courses,
                'faculty': faculty,
                'studentCount': studentCountDict
            }

            return render(request, 'main/facultyCourses.html', context)

        else:
            return redirect('std_login')
    except:

        return redirect('std_login')


# Particular course page (student view)
def course_page(request, code):
    try:
        course = Course.objects.get(code=code)
        if is_student_authorised(request, code):
            try:
                announcements = Announcement.objects.filter(course_code=course)
                assignments = Assignment.objects.filter(
                    course_code=course.code)
                materials = Material.objects.filter(course_code=course.code)

            except:
                announcements = None
                assignments = None
                materials = None

            context = {
                'course': course,
                'announcements': announcements,
                'assignments': assignments[:3],
                'materials': materials,
                'student': Student.objects.get(student_id=request.session['student_id'])
            }

            return render(request, 'main/course.html', context)

        else:
            return redirect('std_login')
    except:
        return render(request, 'error.html')


# Particular course page (faculty view)
def course_page_faculty(request, code):
    course = Course.objects.get(code=code)
    if request.session.get('faculty_id'):
        try:
            announcements = Announcement.objects.filter(course_code=course)
            assignments = Assignment.objects.filter(
                course_code=course.code)
            materials = Material.objects.filter(course_code=course.code)
            studentCount = Student.objects.filter(course=course).count()

        except:
            announcements = None
            assignments = None
            materials = None

        context = {
            'course': course,
            'announcements': announcements,
            'assignments': assignments[:3],
            'materials': materials,
            'faculty': Faculty.objects.get(faculty_id=request.session['faculty_id']),
            'studentCount': studentCount
        }

        return render(request, 'main/faculty_course.html', context)
    else:
        return redirect('std_login')


def error(request):
    return render(request, 'error.html')


# Display user profile(student & faculty)
def profile(request, id):
    try:
        if request.session['student_id'] == str(id):
            student = Student.objects.get(student_id=id)
            return render(request, 'main/profile.html', {'student': student})
        else:
            return redirect('std_login')
    except:
        try:
            if request.session['faculty_id'] == str(id):
                faculty = Faculty.objects.get(faculty_id=id)
                return render(request, 'main/faculty_profile.html', {'faculty': faculty})
            else:
                return redirect('std_login')
        except:
            return render(request, 'error.html')


def addAnnouncement(request, code):
    if is_faculty_authorised(request, code):
        if request.method == 'POST' and request.POST['title'] and request.POST['content']:

            course = Course.objects.get(code=code)
            announcement = Announcement(course_code=course, title=request.POST['title'],
                                        description=request.POST['content'])
            announcement.save()
            return redirect('/faculty/' + str(code))
        else:
            return render(request, 'main/announcement.html', {'course': Course.objects.get(code=code), 'faculty': Faculty.objects.get(faculty_id=request.session['faculty_id'])})
    else:
        return redirect('std_login')


def deleteAnnouncement(request, code, id):
    if is_faculty_authorised(request, code):
        try:
            announcement = Announcement.objects.get(course_code=code, id=id)
            announcement.delete()
            return redirect('/faculty/' + str(code))
        except:
            return redirect('/faculty/' + str(code))
    else:
        return redirect('std_login')


def editAnnouncement(request, code, id):
    if is_faculty_authorised(request, code):
        announcement = Announcement.objects.get(course_code_id=code, id=id)
        context = {
            'announcement': announcement,

main/templates/main/access.html
{% extends 'index.html' %}
{% block title %} {{ course.name }} | eLMS {% endblock title %}
{% block profile %}
{% url 'profile' student.student_id %}
{% endblock %}
{% block user %}
{{student.name}}
{% endblock user %}
{% block allCourses %}
{% url 'courses' %}
{% endblock%}
{% block courses %}
{% url 'myCourses' %}
{% endblock %}
{% block content %}
<div class="container-fluid d-flex" style="min-height: 70vh;">
   <div class="row justify-content-center m-3 align-self-center w-100">
      <div class="col-lg-4 col-sm-12 col-md-6 border p-3 rounded">
         <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
               <label for="key" class="form-label">Enter the access key: </label>
               <input type="number" class="form-control" id="key" name="key" min="0" placeholder="e.g. 1234">
            </div>
            <button type="submit" class="btn btn-sm btn-primary">Submit</button>
         </form>
      </div>
   </div>
</div>
{% endblock %}

main/templates/main/all-assignments.html
{% extends 'index.html' %}
{% load static %}
{% block title %} Assignments | {{ course.name }} | eLMS {% endblock title %}
{% block profile %}
{% url 'profile' faculty.faculty_id %}
{% endblock %}
{% block user %}
{{faculty.name}}
{% endblock user %}
{% block courses %}
{% url 'facultyCourses' %}
{% endblock courses %}
{% block allCourses %}
{% url 'courses' %}
{% endblock %}
{% block content %}
<div class="site-section">
   <!-- navigation links -->
   <div class="container shadow-sm">
      <nav aria-label="breadcrumb">
         <ol class="breadcrumb p-3">
            <li class="breadcrumb-item fw-bold"><a style="color: rgb(10, 10, 48)"
               href="{% url 'facultyCourses' %}">My
               Courses</a>
            </li>
            <li class="breadcrumb-item fw-bold"><a style="color: rgb(10, 10, 48)"
               href="{% url 'faculty' course.code %}">{{ course.name }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Assignment</li>
         </ol>
      </nav>
   </div>
   <!-- navigation links end -->
   <div class="container d-flex flex-wrap flex-column">
      <!-- course name starts -->
      <div class="course-section p-3 m-3 shadow-sm d-flex justify-content-center">
         <h3 class="course_name">{{course.department}}-{{course.code}} : {{course.name}}</h3>
      </div>
      <!-- course name ends -->
      <!-- assignment section starts -->
      <div class="course-section p-3 m-3 shadow">
         <div class="d-flex flex-row justify-content-between edit">
            <h4 class="fw-bold" style="color: rgb(10, 10, 48);"><img src="{% static 'images/icon/open-book.png' %}"
               alt="" style="height:1.5rem"><span style="margin-right: 0.6rem;"></span>Assignment</h4>
            <a class="btn btn-outline-primary" href="{% url 'addAssignment' course.code  %}"><span
               class="mx-2">+</span></a>
         </div>
         <div class="add-announcement">
            {% for assignment in assignments %}
            <!-- individual assignment starts -->
            <hr>
            <a class="text-bold fs-5" href="{% url 'submission' course.code assignment.id %}">
            {{assignment.title}}</a>
            <div class="d-flex justify-content-between mt-3">
               <div class="text-muted">
                  <p>Submitted : {{ assignment.submission_set.count}} / {{ studentCount }} </p>
               </div>
               <div class="fs-6" style="color:grey;">
                  {{assignment.datetime}}
               </div>
            </div>
            <div class="fs-6">
               <p>Submission ends : {{ assignment.deadline }}</p>
            </div>
            <hr>
            <!-- individual assignment ends -->
            {% empty %}
            <hr>
            <h6 style="text-align:center">No assignments given yet</h6>
            <hr>
            {% endfor %}
         </div>
         <div class="text-center fs-6">
            <p>Showing {{ assignments.count}} of {{course.assignment_set.count}} {% if assignments.count == 1 %}assignment {% else %}assignments{% endif %}</p>
         </div>
      </div>
      <!-- assignment section ends -->
   </div>
</div>
{% endblock %}

main/templates/main/faculty_course.html
{% extends 'index.html' %}
{% load static %}
{% block title %} {{ course.name }} | eLMS {% endblock title %}
{% block profile %}
{% url 'profile' faculty.faculty_id %}
{% endblock %}
{% block user %}
{{faculty.name}}
{% endblock user %}
{% block courses %}
{% url 'facultyCourses' %}
{% endblock courses %}
{% block allCourses %}
{% url 'courses' %}
{% endblock %}
{% block content %}
<div class="site-section">
<!-- navigation links -->
<div class="container shadow-sm">
   <nav aria-label="breadcrumb">
      <ol class="breadcrumb p-3">
         <li class="breadcrumb-item fw-bold"><a style="color: rgb(10, 10, 48)"
            href="{% url 'facultyCourses' %}">My Courses</a></li>
         <li class="breadcrumb-item fw-bold"><a class="breadcrumb-item active"
            aria-current="page">{{ course.name }}</a></li>
      </ol>
   </nav>
</div>
<!-- navigation links end -->
<div class="container d-flex flex-wrap flex-column">
   <!-- course name starts -->
   <div class="course-section p-3 m-3 shadow d-flex justify-content-between align-items-center">
      <h3 class="course_name">{{course.department}}-{{course.code}} : {{course.name}}</h3>
      <a class="btn btn-outline-primary btn-sm"
         href="{% url 'discussion' course.code %}">
      Discussion
      </a>
   </div>
   <!-- course name ends -->
   <!-- announcement section starts -->
   <div class="course-section p-3 m-3 shadow">
      <div class="d-flex justify-content-between">
         <h4 class="fw-bold" style="color: rgb(10, 10, 48);"><img src="{% static 'images/icon/megaphone.png' %}"
            alt="" style="height:1.5rem;"><span style="margin-right: 0.6rem;"></span>Announcement
         </h4>
         <a class="btn btn-sm btn-outline-success rounded" style="height:2rem"
            href="{% url 'addAnnouncement' course.code  %}">Create</a>
      </div>
      <div>
         {% for announcement in announcements %}
         <!-- individual announcement starts -->
         <hr>
         <h4>{{announcement.title}}</h4>
         <div class="fs-6 text-break">{{announcement.description}}</div>
         <div class="announcement-cont d-flex justify-content-between">
            <div>
               <button type="button" class="btn btn-sm btn-outline-danger" data-bs-toggle="modal"
                  data-bs-target="#staticBackdrop">
               Delete
               </button>
               <!-- Popup -->
               <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false"
                  tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered">
                     <div class="modal-content">
                        <div class="modal-header" style="border:none">
                           <button type="button" class="btn-close" data-bs-dismiss="modal"
                              aria-label="Close">
                           </button>
                        </div>
                        <div class="modal-body fs-6">
                           Are you sure you want to delete this announcement?
                        </div>
                        <div class="modal-footer" style="border:none">
                           <button type="button" data-bs-dismiss="modal"
                              class="btn btn-sm ">Cancel</button>
                           <a class="btn btn-sm btn-primary"
                              href="{% url 'deleteAnnouncement' course.code announcement.id %}">Confirm</a>
                        </div>
                     </div>
                  </div>
               </div>
               <a class="btn btn-sm btn-outline-primary px-3"
                  href="{% url 'editAnnouncement' course.code announcement.id %}">Edit</a>
            </div>
            <div class="add-announcement" style="color:grey;">
               {{announcement.datetime}}
            </div>
         </div>
         <hr>
         <!-- individual announcement ends-->
         {% empty %}
         <hr>
         <h6 style="text-align:center">No announcements given yet</h6>
         <hr>
         {% endfor %}
      </div>
   </div>
   <!-- announcement section ends -->
   <!-- assignment section starts -->
   <div class="course-section p-3 m-3 shadow">
      <div class="d-flex flex-row justify-content-between edit">
         <h4 class="fw-bold" style="color: rgb(10, 10, 48);"><img src="{% static 'images/icon/open-book.png' %}"
            alt="" style="height:1.5rem"><span style="margin-right: 0.6rem;"></span>Assignment</h4>
         <a class="btn btn-sm btn-outline-success rounded" style="height:2rem"
            href="{% url 'addAssignment' course.code %}">Create</a>
      </div>
      <div class="add-announcement">
         {% for assignment in assignments %}
         <!-- individual assignment starts -->
         <hr>
         <a class="text-bold fs-5" href="{% url 'submission' course.code assignment.id %}">
         {{assignment.title}}</a>
         <div class="d-flex justify-content-between mt-3">
            <div class="text-muted">
               <p>Submitted : {{ assignment.submission_set.count}} / {{ studentCount }} </p>
            </div>
            <div class="fs-6" style="color:grey;">
               {{assignment.datetime}}
            </div>
         </div>
         <div class="fs-6">
            <p>Submission ends : {{ assignment.deadline }}</p>
         </div>
         <hr>
         <!-- individual assignment ends -->
         {% empty %}
         <hr>
         <h6 style="text-align:center">No assignments given yet</h6>
         <hr>
         {% endfor %}
      </div>
      <div class="text-center fs-6">
         {% if assignments %}
         <p>Showing {{ assignments.count}} of {{course.assignment_set.count}}
            {% if assignments.count == 1 %}assignment {% else %}assignments{% endif %}
         </p>
         <a href=" {% url 'allAssignments' course.code %} ">Show all</a>
         {% endif %}
      </div>
   </div>
   <!-- assignment section ends -->
   <!-- course material section starts -->
   <div class="course-section p-3 m-3 shadow">
      <div class="d-flex flex-row justify-content-between edit">
         <h4 class="fw-bold" style="color: rgb(10, 10, 48);"><img src="{% static 'images/icon/folder.png' %}"
            alt="" style="height:1.5rem"><span style="margin-right: 0.6rem;"></span>Course Material</h4>
         <a class="btn btn-sm btn-outline-success rounded" style="height:2rem"
            href="{% url 'addCourseMaterial' course.code  %}"><span class="px-2">Add</span></a>
      </div>
      <div class="add-announcement">
         {% for material in materials  %}
         <!-- individual material starts -->
         <hr>
         <a class="add-announcement" href="{{ material.file.url }}">{{material.title}}</a><br>
         <div class="fs-6 text-break mb-2">{{material.description}}</div>
         <!-- Popup -->
         <div class="modal fade" id="materialDel" data-bs-backdrop="static" data-bs-keyboard="false"
            tabindex="-1" aria-labelledby="materialBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
               <div class="modal-content">
                  <div class="modal-header" style="border:none">
                     <button type="button" class="btn-close" data-bs-dismiss="modal"
                        aria-label="Close"></button>
                  </div>
                  <div class="modal-body fs-6">
                     Are you sure you want to remove this item?
                  </div>
                  <div class="modal-footer" style="border:none">
                     <button type="button" class="btn btn-sm "
                        data-bs-dismiss="modal">Cancel</button>
                     <a class="btn btn-sm btn-primary"
                        href="{% url 'deleteCourseMaterial' course.code material.id %}">Confirm</a>
                  </div>
               </div>
            </div>
         </div>
         <div class="d-flex flex-row justify-content-between">
            <button type="button" class="btn btn-sm btn-outline-danger" data-bs-toggle="modal"
               data-bs-target="#materialDel">
            Remove
            </button>
            <div class="add-announcement" style="color:grey;">
               {{material.datetime}}
            </div>
         </div>
         <hr>
         {% empty %}
         <hr>
         <h6 style="text-align:center">Course materials not available</h6>
         <hr>
         {% endfor %}
         <!-- individual material ends -->
      </div>
   </div>
   <!-- course material section ends-->
</div>
{% endblock %}